  
name: Test de integración
on: push

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    outputs:
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py